// THIN WRAPPER FOR CLIENT-INITIATED /api CALLS. ON WEB IT'S A SAME-ORIGIN fetch — THE httpOnly SESSION
// COOKIE RIDES ALONG AUTOMATICALLY, SO NOTHING EXTRA IS NEEDED. PHASE 6 EXTENDS THIS FOR THE NATIVE
// (CAPACITOR) BUILD: PREPEND PUBLIC_API_BASE AND ATTACH THE FIREBASE ID TOKEN AS `Authorization: Bearer`
// (NO COOKIES CROSS-ORIGIN). ROUTING CLIENT FETCHES THROUGH HERE NOW MEANS THE NATIVE BEHAVIOUR IS A
// ONE-FILE CHANGE LATER.
export function apiFetch(path: string, init?: RequestInit): Promise<Response> {
	return fetch(path, init);
}
