// -- CONSTANTS -- //

// TRAILING SLASH CONVENTION — APPLIES TO ALL ROUTES
export const trailingSlash = 'always';

// THE NODE (WEB) BUILD SSRs FOR FAST FIRST PAINT + SEO. THE CAPACITOR BUILD (BUILD_TARGET=capacitor →
// __CAPACITOR_BUILD__) IS A PURE CLIENT SPA (ssr=false) THAT TALKS TO THE HOSTED /api WITH A BEARER TOKEN —
// SO NO SERVER LOAD IS REACHED IN THE NATIVE BUNDLE (RELIES ON THE PHASE-1 /app DECOUPLING).
export const ssr = !__CAPACITOR_BUILD__;
export const prerender = false;
